Started on configfile gen

diff --git a/corpses b/corpses
--- a/corpses
+++ b/corpses
@@ -93,8 +93,14 @@ fi
 
 echo -n "  Checking for config ... "
 if [ -f "server/config.json" ]; then
-	echo -ne "\033[32mfound.\033[0m"
-	echo -e "\r\033[32m\xe2\x9c\x94\033[0m"
+	if node scripts/checkconfig.js ; then
+		echo -ne "\033[okay.\033[0m"
+		echo -e "\r\033[32m\xe2\x9c\x94\033[0m"
+	else
+		echo -ne "\033[31mfound but invalid!\033[0m Please add the missing keys."
+		echo -e "\r\033[31m\xe2\x9c\x98\033[0m"
+		exit 1
+	fi
 else
 	echo -ne "\033[31mnot found!\033[0m Please copy the file \"server/config.json.example\" to \"server/config.json\" and edit it according to your needs."
 	echo -e "\r\033[31m\xe2\x9c\x98\033[0m"
